### ISSUE TITLE
Access is denied issue in GUI jar file.

### ISSUE THREAD

**Issue by HongJiancheng** [nus-tic4002-AY2021S2/forum#6]
Just released my build has an issue with accessing file after implementing GUI.
Have tried multiple methods:
* Run java -jar Duke.jar with cmd that run as administrator.
* Let the program create the data folder from the scracth (worked for CLI version)

Screenshot of the issue from my GUI:
![image](https://user-images.githubusercontent.com/43083270/106350313-9cb99780-630f-11eb-93d0-4ffced9128e1.png)

**Comment by Jh123x** [comment]
Hi , can you try specifying a relative path instead of absolute path?

Can you take a screenshot of your code used for reading files?

**Comment by Diwu-Yi** [comment]
Hi, @HongJiancheng  it is likely that the issue lies in the way of how the java class reads the storage file(i.e. your code). It is not likely that the problem is with the jar file or how to run the jar file (i.e. either as administrator or not).

[Here] is a post on a very similar problem, perhaps the solutions will work for you as well.
[https://stackoverflow.com/questions/14209085/how-to-define-a-relative-path-in-java](url)

**Comment by richardcom** [comment]
Hi, from your description, I think that the path D:/School/Data might be the original file path when you run ur application in the development process. As u might have moved the location of your jar file, the path is no longer valid. Do you mind providing more info abt how u code about the file access path?

**Comment by HongJiancheng** [comment]
Hi all, many thanks for your timely advice!
I have attached the screenshot part of my storage class file, which handles the file IO.
![Screenshot_20210130_161833_com android chrome](https://user-images.githubusercontent.com/43083270/106351449-3769a480-6317-11eb-809f-60c0219c4c79.jpg)

I have implemented the relative file path before hand, but it sill result in the issue above mentioned. Thus want to find help, haha.

**Comment by Jh123x** [comment]
https://www.tutorialspoint.com/java/java_files_io.htm

Hi maybe you can take a look at this and use filereader to read the file?

**Comment by Diwu-Yi** [comment]
Hi, @HongJiancheng indeed you have implemented relative file path. In this case I suggest that you try use nio.file.Path to try to solve the problem because perhaps the file is not properly loaded from the `storageFilePath` as a string. By using nio.file.Path, you can declare something like:

<img width="830" alt="Screenshot 2021-01-30 at 4 37 42 PM" src="https://user-images.githubusercontent.com/59159857/106351810-7b5da900-6319-11eb-93c7-d406e8efd27f.png">

Then, reading the file is similar to what you have done:
check existence:
<img width="502" alt="Screenshot 2021-01-30 at 4 40 26 PM" src="https://user-images.githubusercontent.com/59159857/106351863-dd1e1300-6319-11eb-8699-bd7520fd9295.png">
access:
<img width="408" alt="Screenshot 2021-01-30 at 4 38 56 PM" src="https://user-images.githubusercontent.com/59159857/106351833-a7792a00-6319-11eb-8c5a-2b533eb6c270.png">

However I am not entirely sure that this will solve the problem as I am on a different OS.
Hope it helps.

**Comment by HongJiancheng** [comment]
Hi all, noted with many thanks! Will try tonight and update about the issue has been resolved or not.

**Comment by richardcom** [comment]
Thank @Jh123x and @Diwu-Yi for their very detailed explanation. Also another alternative way is to first try not to create a directory but just a new file Duke and see if it works. Part of the sample code is provided below:
![image](https://user-images.githubusercontent.com/65701775/106353142-5ff79b80-6323-11eb-8d82-e4bc8bf76289.png)

![image](https://user-images.githubusercontent.com/65701775/106353149-6dad2100-6323-11eb-8e9f-08dc4a91057f.png)

**Comment by HongJiancheng** [comment]
> Hi, @HongJiancheng indeed you have implemented relative file path. In this case I suggest that you try use nio.file.Path to try to solve the problem because perhaps the file is not properly loaded from the `storageFilePath` as a string. By using nio.file.Path, you can declare something like:
> 
> <img alt="Screenshot 2021-01-30 at 4 37 42 PM" width="830" src="https://user-images.githubusercontent.com/59159857/106351810-7b5da900-6319-11eb-93c7-d406e8efd27f.png">
> 
> Then, reading the file is similar to what you have done:
> check existence:
> <img alt="Screenshot 2021-01-30 at 4 40 26 PM" width="502" src="https://user-images.githubusercontent.com/59159857/106351863-dd1e1300-6319-11eb-8699-bd7520fd9295.png">
> access:
> <img alt="Screenshot 2021-01-30 at 4 38 56 PM" width="408" src="https://user-images.githubusercontent.com/59159857/106351833-a7792a00-6319-11eb-8c5a-2b533eb6c270.png">
> 
> However I am not entirely sure that this will solve the problem as I am on a different OS.
> Hope it helps.

Awesome! Have tried nio.file.Path, and it works perfectly! You saved my day!

Thanks all others' help, too!

Here is the screenshot of my working Duke, haha.
![image](https://user-images.githubusercontent.com/43083270/106375092-275bce80-63c4-11eb-89ff-972bec5ce8ab.png)

**Comment by damithc** [comment]
Good to hear that @HongJiancheng 
Thanks everyone for pitching in.
